{% set name = "pdal-c" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PDAL/CAPI/archive/refs/tags/v{{version}}.tar.gz
  sha256: 07b45e8b6094f358e75a9743eef6c04ca1cb95dff1da86915a35be69289408d2

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
  host:
    - pdal
  run:
    - {{ pin_compatible('pdal', max_pin='x.x') }}

test:
  commands:
    - test_pdalc

about:
  home: https://github.com/pdal/capi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: C API for the PDAL Point Cloud Data Abstraction Layer
  description: |
    PDAL is a C++ library for translating and manipulating point cloud data. This package provides a C API to the package.
  doc_url: https://pdal.io/CAPI/doxygen/html/index.html
  dev_url: https://github.com/pdal/capi

extra:
  recipe-maintainers:
    - Runette
    - hobu
