{% set name = "pdal-c" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/PDAL/CAPI.git

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [not win]
    - ninja # [win]
  host:
    - pdal
  run:
    - {{ pin_compatible('pdal', max_pin='x.x') }}

test:
  commands:
    - test_pdalc

about:
  home: https://github.com/pdal/capi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: C API for the PDAL Point Cloud Data Abstraction Layer
  description: |
    PDAL is a C++ library for translating and manipulating point cloud data. This package provides a C API to the package.
  doc_url: https://pdal.io/CAPI/doxygen/html/index.html
  dev_url: https://github.com/pdal/capi

extra:
  recipe-maintainers:
    - Runette
    - hobu
